### PR TITLE
Add possibility to specify UNIX file permissions

### PR DESCRIPTION
**Pull request by mbiggio**

### CODE REVIEW

**Comment by Ploppz** [comment]
Looks good, but can you add a test? Then I'll merge.

**Comment by Ploppz** [comment]
Looks good, but can you add a test? Then I'll merge.

**Comment by mbiggio** [comment]
Thanks for reviewing, I actually caught a bug in the previous code that permissions were not set correctly on the rotated file. Should be ok now

**Comment by Ploppz** [comment]
Thanks, I'll merge it now, then before any release I'll try to set up cross-platform testing using Github Actions.

**Pull request merged**
