### PR TITLE
Fixed bug where a log file's size was used as its line count

### PR DESCRIPTION
**Pull request by mmponn**

### CODE REVIEW

**Comment by Ploppz** [comment]
Good catch! I indeed only had ContentLimit::Bytes* in mind when I wrote that

**Comment by Ploppz** [comment]
Changes look good and tests pass. Is it ready for merge?

**Comment by mmponn** [comment]
Yep!

**Comment by mmponn** [comment]
Although I didn't bump the project version. Please advise if (and how) you want me to change it.

**Comment by mmponn** [comment]
Switched to private GitHub email

**Comment by Ploppz** [comment]
No worries, I can bump the version and publish

**Pull request merged**
